name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - develop   # 👈 add more branches if you want separate deployments

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build
        env:                             # 👈 Pass branch name into Vite build
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}   # each branch → separate folder
